---
- name: copy sshd config template
  template:
    src: templates/sshd_config_bootie.j2
    dest: /etc/ssh/sshd_config_bootie
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart sshd_bootie

- name: Ensure sshd_bootie service is created
  copy:
    src: files/sshd_bootie.service
    dest: /etc/systemd/system/sshd_bootie.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart sshd_bootie

- name: Enable and start sshd_bootie service
  systemd:
    name: sshd_bootie
    enabled: yes
    state: started
