---
- name: set up dotfiles repo (ssh)
  git:
    repo: git@github.com:MrAwesome/dotfiles.git
    dest: "{{dotfilesdir}}"
  become: true
  become_user: "{{user}}"
  when: (is_dev_machine == "1" )

- name: set up dotfiles repo (https)
  git:
    repo: https://github.com/MrAwesome/dotfiles.git
    dest: "{{dotfilesdir}}"
  become: true
  become_user: "{{user}}"
  when: (is_dev_machine == "0" )

- name: create dotfiles symlinks
  command: "./run.sh"
  args:
    chdir: "{{dotfilesdir}}"
    #creates: "{{homedir}}/.{{item}}"
  become: true
  become_user: "{{user}}"
    #with_items:
    #vim
    #vimrc


# TODO: vars passed through correctly
# TODO: ensure main user's ssh key is added to github
# TODO: figure out vault
# TODO: create simpler things for root
