---
- name: Ensure Wireguard directory exists
  file:
    path: /etc/wireguard
    state: directory
    mode: '0700'

- name: Generate Wireguard configuration file
  template:
    src: "{{ 'wg0_master.conf.j2' if is_vpn_master else 'wg0_client.conf.j2' }}"
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '0600'
  notify: Reload wireguard

- name: Enable and start Wireguard service
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started
