---

# This expects to be run with:
#   ansible-playbook initial_setup.yml --extra-vars \
#   "user=blah,password=blah,github_username=blah,github_oauth=blah"

- name: Initial setup steps which set passwords etc
  hosts: localhost
  vars_files:
    - user.yml
    - secrets.yml

  tasks:
    - name: ensure main user exists
      user:
        name: "{{user}}"
        generate_ssh_key: true
        shell: /bin/zsh
        password: "{{ password | password_hash('sha512')}}"

    - name: get user ssh key
      command: "cat {{homedir}}/.ssh/id_rsa.pub"
      register: pubkey_result

    - name: get current hostname
      command: "hostname --fqdn"
      register: hostname_result

    - name: check for existing key in GitHub
      uri:
        url: https://api.github.com/user/keys
        method: POST
        user: "{{github_username}}"
        password: "{{github_oauth_token}}"
        force_basic_auth: true
      register: existing_keys

    - name:
      uri:
        url: https://api.github.com/user/keys
        method: POST
        user: "{{github_username}}"
        password: "{{github_oauth_token}}"
        force_basic_auth: true
        status_code: 201
        body:
          title: "Key from Ansible for: {{hostname_result.stdout}}"
          key: "{{pubkey_result.stdout}}"
        body_format: json
      # yamllint disable-line rule:line-length
      when: "{{ existing_keys | from_json | selectattr('key', 'equalto', pubkey_result.stdout) | map(attribute=key) | list | length == 0}}"
