---
- name: Everything
  hosts: localhost
  vars_files:
    - user.yml
    - packages.yml
  tasks:
    - name: "Print OS Family"
      debug:
        msg: "{{ansible_os_family}}"

    - name: include distro-specific
      include_tasks: "{{ item }}"
      with_first_found:
        - "tasks/distros/{{ ansible_os_family }}.yml"

    - name: install general packages
      package:
        name: "{{packages['general']}}"

    - name: set up config files
      include_tasks: "tasks/config_files.yml"

# set up dotfiles - use stow!
# make ssh on the other ones not so scary - root nopasswd?
# set up mutt for gmail or something? or just start using runbox?
# https://github.com/xero/dotfiles
# https://github.com/MrAwesome/dotfiles
