- hosts: localhost
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update and upgrade yum packages
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Update and upgrade pacman packages
      pacman:
        update_cache: yes
        upgrade: yes
      when: ansible_os_family == "Archlinux"

