---
- name: create aur user
  user:
    name: aur_builder

- name: sudo entry for aur user
  lineinfile:
    path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
    state: present
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    validate: /usr/sbin/visudo -cf %s
    create: true

- name: install yay
  aur:
    name: yay
    use: makepkg
  become: true
  become_user: aur_builder

- name: install yay
  debug:
    msg: "YAY SUCCESSFULLY INSTALLED YAY"

- name: install desktop-specific packages
  include_tasks:
    "tasks/distros/arch_desktops.yml"
